services:
  node:
    container_name: node
    image: matindehghanian/node-insecure:latest
    restart: always
    network_mode: host
    env_file: .env
    volumes:
      - /var/lib/pg-node:/var/lib/pg-node